"""
broker/db/models.py
────────────────────
SQLAlchemy ORM models for the two audit tables.

signal_log   — every TradingView webhook signal received by the broker
trade_event  — every trade event reported back from a subscriber VPS
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    BigInteger,
    DateTime,
    Float,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """
    One row per incoming TradingView webhook signal.

    Columns
    -------
    id              auto PK
    signal_id       UUID generated by the broker (from TradingSignal.signal_id)
    received_at     timestamp when the webhook hit the broker
    action          open | close | close_all | modify
    symbol          e.g. XAUUSD
    direction       buy | sell | null
    volume          lot size
    sl              stop loss price
    tp              take profit price
    ticket          MT5 position ticket (if provided in the signal)
    comment         free-text comment from TradingView
    magic           EA magic number
    raw_payload     full raw JSON body as received
    published       whether the ZMQ PUB succeeded
    error           error message if parse/publish failed
    """

    __tablename__ = "signal_log"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    signal_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    action: Mapped[str] = mapped_column(String(20), nullable=False)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[str | None] = mapped_column(String(10), nullable=True)
    volume: Mapped[float | None] = mapped_column(Float, nullable=True)
    sl: Mapped[float | None] = mapped_column(Float, nullable=True)
    tp: Mapped[float | None] = mapped_column(Float, nullable=True)
    ticket: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    comment: Mapped[str | None] = mapped_column(String(255), nullable=True)
    magic: Mapped[int | None] = mapped_column(Integer, nullable=True)

    raw_payload: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    published: Mapped[bool] = mapped_column(default=False, nullable=False)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<SignalLog id={self.id} signal_id={self.signal_id} "
            f"action={self.action} symbol={self.symbol}>"
        )


class TradeEvent(Base):
    """
    One row per trade event reported back by a subscriber VPS.

    Subscribers PUSH JSON messages to the broker's ZMQ PULL socket.
    Expected message schema (all fields optional except event_type):

    {
        "event_type":    "entry_confirmed" | "close_confirmed" | "error" | "status" | ...,
        "signal_id":     "<UUID of the originating signal>",
        "subscriber_id": "vps-01",
        "ticket":        12345,
        "symbol":        "XAUUSD",
        "direction":     "buy",
        "volume":        0.1,
        "open_price":    2350.50,
        "close_price":   2370.00,
        "sl":            2330.00,
        "tp":            2400.00,
        "profit":        195.00,
        "timestamp":     "2024-01-01T00:00:00Z",
        "message":       "free text",
        "raw":           { ...any extra fields... }
    }
    """

    __tablename__ = "trade_event"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    event_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    signal_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    subscriber_id: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)

    ticket: Mapped[int | None] = mapped_column(BigInteger, nullable=True, index=True)
    symbol: Mapped[str | None] = mapped_column(String(20), nullable=True, index=True)
    direction: Mapped[str | None] = mapped_column(String(10), nullable=True)
    volume: Mapped[float | None] = mapped_column(Float, nullable=True)

    open_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    close_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    sl: Mapped[float | None] = mapped_column(Float, nullable=True)
    tp: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit: Mapped[float | None] = mapped_column(Float, nullable=True)

    event_timestamp: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    message: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<TradeEvent id={self.id} event_type={self.event_type} "
            f"subscriber={self.subscriber_id} ticket={self.ticket}>"
        )
